### ISSUE TITLE
Verificar disponibilidade da API antes de enviar requisições

### ISSUE THREAD

**Issue by rn4n** [micebot/discord#11]
Por conta do Heroku desligar nossa aplicação depois de 30min, pode ser que quando o usuário for utilizar o bot, a API esteja off e com isso o comando se perde.

Antes de enviar a requisição do comando dado, é melhor dar um GET no endpoint com um timeout baixo para "acordar" a aplicação no Heroku.

Outra alternativa é ficar dando GET de tempos em tempos para que a API nunca desligue.

**Comment by micebot-user** [comment]
Criei uma aplicação para ficar realizando requisições para o servidor de desenvolvimento e produção a cada 10min:

https://github.com/micebot/wake-me-up
