### ISSUE TITLE
Adicionar Github Actions

### ISSUE THREAD

**Issue by milafrn** [micebot/discord#7]
Hoje estamos usando Gitlab para CI/CD.

- Mudar para o Github Actions.

**Comment by milafrn** [comment]
Criei o CI na branch development

168c1a7b8e55f796df57271ce148a5397a513f2f

**Comment by rn4n** [comment]
Reabrindo, o pipeline inteiro deve ser migrado.

https://gitlab.com/micebot/discord-ci/-/pipelines/171868237

**Comment by jake-walker** [comment]
I'd like to look at this one
